project_id = "ygdgbapodmoxklcssjzr"

[functions.generate-action-plan]
verify_jwt = false

[functions.generate-faq]
verify_jwt = false

[functions.collect-reviews]
verify_jwt = false

[functions.crawl-lge-reviews]
verify_jwt = false

[functions.collect-youtube-comments]
verify_jwt = false
