INSERT INTO reviews (product_id, source, title, content, author, rating, sentiment, sentiment_score, source_url, emotion_category, emotion_intensity, user_type, content_type, platform_type, external_id) VALUES
-- S95AR Soundbar reviews
((SELECT id FROM products WHERE model_number = 'S95AR'), 'rtings', 'RTINGS: LG S95AR Soundbar Review', 'The LG S95AR is great for mixed usage. The soundbar supports many features, including channel, treble, and bass level adjustments, dialogue enhancement, and Dolby Atmos decoding. It has a 9.1.5 channel setup with 17 speakers that deliver impressive 3D spatial sound. AI Room Calibration automatically adjusts audio based on room acoustics for optimal performance.', 'RTINGS', 4, 'positive', 0.85, 'https://www.rtings.com/soundbar/reviews/lg/s95ar', 'impressed', 4, 'reviewer', 'review', 'review_site', 'rtings-s95ar-001'),
((SELECT id FROM products WHERE model_number = 'S95AR'), 'reddit', 'RTINGs LG S95AR Review scores highest of any soundbar tested', 'Sub bass is, as reported, a bit underwhelming by comparison to my Bose one but other than that I find the sound quality impressive and love the surround sound effect. The Dolby Atmos support is phenomenal for movies. WOW Orchestra with my LG OLED creates a truly immersive experience.', 'reddit_user', 4, 'positive', 0.82, 'https://www.reddit.com/r/Soundbars/comments/1mloeoo/', 'satisfaction', 4, 'actual_user', 'review', 'community', 'reddit-s95ar-001'),
((SELECT id FROM products WHERE model_number = 'S95AR'), 'youtube', 'LG S95AR Review: A Superior Successor', 'The S95AR builds on the success of its predecessor with an upgraded 9.1.5 channel system. Triple up-firing speakers deliver clear dialogue as if coming directly from the screen. The subwoofer delivers powerful, distortion-free bass. However, the price point remains premium and may not suit budget-conscious buyers.', 'YouTube Reviewer', 4, 'positive', 0.78, 'https://www.youtube.com/watch?v=d057SJdEvWc', 'impressed', 4, 'reviewer', 'review', 'video', 'yt-s95ar-001'),

-- S90TR Soundbar
((SELECT id FROM products WHERE model_number = 'S90TR'), 'rtings', 'LG S90TR Home Theater Soundbar', 'The LG S90TR is ideal for entertainment buffs who enjoy intense gaming and immersive movie nights. This model offers top-tier surround sound with a wireless subwoofer and rear speakers. Perfect compatibility with LG OLED and QNED TVs. The WOW Orchestra feature synchronizes TV and soundbar speakers for a harmonized audio output.', 'RTINGS', 4, 'positive', 0.80, 'https://www.rtings.com/soundbar/reviews/lg/s90tr', 'impressed', 4, 'reviewer', 'review', 'review_site', 'rtings-s90tr-001'),

-- SC9S Soundbar
((SELECT id FROM products WHERE model_number = 'SC9S'), 'reddit', 'Is LG SC9S really as bad as What HIFI describes?', 'The SC9S has great adjustability through the LG Sound Bar app and it really should be used with the sound bar. The OLED Synergy Bracket is included in the box for custom TV mounting. It excels in bass response for powerful action scenes. Great value for apartment-sized rooms.', 'reddit_user', 4, 'positive', 0.75, 'https://www.reddit.com/r/Soundbars/comments/16fcso5/', 'satisfaction', 3, 'actual_user', 'review', 'community', 'reddit-sc9s-001'),
((SELECT id FROM products WHERE model_number = 'SC9S'), 'cnet', 'WIRED: LG SC9S Soundbar Review', 'The SC9S excels when it comes to bass response in powerful action scenes, from the pounding pop of Ant-Mans flying ants to the booming explosions in Skyfall. The OLED Synergy design creates a clean, integrated look with compatible LG TVs. Sound quality punches above its weight for the price point.', 'WIRED', 4, 'positive', 0.80, 'https://www.wired.com/review/lg-sc9s/', 'impressed', 4, 'reviewer', 'review', 'review_site', 'wired-sc9s-001'),

-- SG10TY Soundbar
((SELECT id FROM products WHERE model_number = 'SG10TY'), 'trusted_reviews', 'LG SG10TY Soundbar for Interior Enthusiasts', 'The SG10TY is designed to match the aesthetic of LG OLED TVs with a premium look in a compact form. Ideal for minimalist or wall-mounted layouts. The sound quality is solid for its size with Dolby Atmos support. Perfect choice for those prioritizing design integration over raw power.', 'Trusted Reviews', 4, 'positive', 0.76, 'https://www.lg.com/us/soundbars/lg-sg10ty-soundbar', 'satisfaction', 3, 'reviewer', 'review', 'review_site', 'tr-sg10ty-001'),

-- xboom Bounce
((SELECT id FROM products WHERE model_number = 'XBOOM-BOUNCE'), 'rtings', 'RTINGS: LG xboom Bounce Speaker Review', 'The LG xboom Bounce is very portable with an IP67 rating against water and dust. It features up to 30 hours of playback and passed 7 military-standard durability tests. Sound is bold and clear even outdoors. Adaptive technologies deliver personalized sound based on genre and environment.', 'RTINGS', 4, 'positive', 0.78, 'https://www.rtings.com/speaker/reviews/lg/xboom-bounce-bluetooth', 'impressed', 3, 'reviewer', 'review', 'review_site', 'rtings-bounce-001'),
((SELECT id FROM products WHERE model_number = 'XBOOM-BOUNCE'), 'cnet', 'PCMag: xboom Bounce Impressive Audio', 'The LG Xboom Bounce is a portable Bluetooth speaker that produces quality audio, has good battery life, and is simple to operate. Its unique design and deep customization options set it apart from the usual crowd. Battery life holds up impressively well at up to 30 hours.', 'PCMag', 4, 'positive', 0.80, 'https://www.pcmag.com/reviews/lg-xboom-bounce', 'impressed', 4, 'reviewer', 'review', 'review_site', 'pcmag-bounce-001'),
((SELECT id FROM products WHERE model_number = 'XBOOM-BOUNCE'), 'bestreviews', 'SoundGuys: xboom Bounce Unusual Looks, Surprisingly Good Sound', 'Its unique design and deep customization options set it apart from the usual crowd, and battery life holds up impressively well. The IP67 rating means it survives pool parties and beach trips. The Red Dot 2025 award-winning design is eye-catching. Bass response is solid for its compact size.', 'SoundGuys', 4, 'positive', 0.82, 'https://www.soundguys.com/lg-xboom-bounce-review-147284/', 'impressed', 4, 'reviewer', 'review', 'review_site', 'sg-bounce-001'),

-- xboom Grab
((SELECT id FROM products WHERE model_number = 'XBOOM-GRAB'), 'rtings', 'RTINGS: LG xboom Grab Speaker Review', 'The LG xboom Grab is sub-par for watching videos due to compact size limiting volume for larger rooms. However as a portable speaker it excels with IP67 rating, racetrack woofer, dome tweeter and radiators delivering vibrant sound on the go. Adjustable straps make it easy to carry anywhere.', 'RTINGS', 3, 'neutral', 0.60, 'https://www.rtings.com/speaker/reviews/lg/xboom-grab', 'mixed', 3, 'reviewer', 'review', 'review_site', 'rtings-grab-001'),
((SELECT id FROM products WHERE model_number = 'XBOOM-GRAB'), 'bestreviews', 'SoundGuys: Is xboom Grab the best JBL Flip alternative?', 'The LG xboom Grab is a solid alternative to your everyday JBL or Bose speaker. It is tough with an IP67 rating, compact enough to take anywhere. Sound quality is surprisingly good for the size. The adaptive sound technology adjusts based on genre and listening environment which is a nice touch.', 'SoundGuys', 4, 'positive', 0.78, 'https://www.soundguys.com/lg-xboom-grab-review-146889/', 'impressed', 3, 'reviewer', 'review', 'review_site', 'sg-grab-001'),
((SELECT id FROM products WHERE model_number = 'XBOOM-GRAB'), 'youtube', 'LG XBOOM Grab Better Than JBL Flip 7?', 'I kinda like LG as a brand. The xboom Grab competes directly with JBL Flip 7 and holds its own. Build quality is excellent with military-grade durability testing. Sound signature is bass-forward which works great for pop and hip-hop. The will.i.am collaboration brings a unique design aesthetic.', 'YouTube Reviewer', 4, 'positive', 0.75, 'https://www.youtube.com/watch?v=pvjIlFA7TWU', 'satisfaction', 3, 'reviewer', 'review', 'video', 'yt-grab-001'),

-- xboom Stage 301
((SELECT id FROM products WHERE model_number = 'XBOOM-STAGE-301'), 'rtings', 'RTINGS: LG xboom Stage 301 Review', 'The LG xboom Stage 301 is decent for music with several EQ presets alongside a three-band graphic EQ. The 6.5 inch woofer and dual 2.5 inch midrange drivers deliver room-filling sound. Battery lasts up to 12 hours with a removable battery. Mic and guitar input for karaoke and performances.', 'RTINGS', 4, 'positive', 0.75, 'https://www.rtings.com/speaker/reviews/lg/xboom-stage-301', 'satisfaction', 3, 'reviewer', 'review', 'review_site', 'rtings-stage301-001'),
((SELECT id FROM products WHERE model_number = 'XBOOM-STAGE-301'), 'reddit', 'DJ and Producer Review of xboom Stage 301', 'First impression when the LG xboom Stage 301 arrived: its pretty big and pretty hefty too but in a good solid way. The sound is strong and powerful, with bass you can feel in your body. At the loudest volume settings there is a bit of compression. Great party speaker for outdoor events.', 'reddit_user', 4, 'positive', 0.80, 'https://www.reddit.com/r/Bluetooth_Speakers/comments/1piij39/', 'impressed', 4, 'actual_user', 'review', 'community', 'reddit-stage301-001'),
((SELECT id FROM products WHERE model_number = 'XBOOM-STAGE-301'), 'bestreviews', 'Boring Text Reviews: Hands-on xboom Stage 301 Boombox', 'The sound is strong and powerful, with bass you can feel in your body. At the loudest volume settings there is a bit of compression so you lose some detail. The removable battery is a game changer for outdoor events. Upright or tilted positioning gives flexibility in placement. LED lighting adds party atmosphere.', 'Boring Text Reviews', 4, 'positive', 0.77, 'https://www.boringtextreviews.com/2025/09/12/hands-on-with-lgs-xboom-stage-301-boombox/', 'impressed', 3, 'reviewer', 'review', 'review_site', 'btr-stage301-001'),

-- xboom Buds
((SELECT id FROM products WHERE model_number = 'XBOOM-BUDS'), 'trusted_reviews', 'What Hi-Fi: LG Xboom Buds 2025 Review', 'They are a reasonable effort, but the LG Xboom Buds cannot match their similarly priced rivals sonic capabilities. The graphene drivers reduce distortion and 3-mic ANC works adequately. Up to 30 hours of playback with quick charge is convenient. Stabilizing fins ensure a comfortable fit during exercise.', 'What Hi-Fi', 3, 'neutral', 0.55, 'https://www.whathifi.com/headphones/wireless-earbuds/lg-xboom-buds-2025', 'mixed', 3, 'reviewer', 'review', 'review_site', 'whf-buds-001'),
((SELECT id FROM products WHERE model_number = 'XBOOM-BUDS'), 'reddit', 'LG xboom Buds Review on r/LG_UserHub', 'The xboom Buds never slipped out and stayed secure even during physical activity. I only had to change the earbud foams to the smallest size. Sound quality is bass-heavy which suits my taste. The Dolby Atmos support when connected to LG TV is a unique selling point. Good value for money overall.', 'reddit_user', 4, 'positive', 0.78, 'https://www.reddit.com/r/LG_UserHub/comments/1l3ufjj/', 'satisfaction', 3, 'actual_user', 'review', 'community', 'reddit-buds-001'),
((SELECT id FROM products WHERE model_number = 'XBOOM-BUDS'), 'cnet', 'TechRadar: LG xboom Buds bass-heavy earbuds tuned by will.i.am', 'LGs latest earbuds are not the most suave, but their broad feature-set and solid sound still makes them worth a look. Bass response is emphasized due to will.i.am tuning. ANC performance is adequate but not class-leading. The LG TV integration with Dolby Atmos head tracking is the standout feature that differentiates these from competitors.', 'TechRadar', 3, 'positive', 0.70, 'https://www.techradar.com/audio/earbuds-airpods/lg-xboom-buds-review', 'satisfaction', 3, 'reviewer', 'review', 'review_site', 'tr-buds-001'),

-- S77S Soundbar
((SELECT id FROM products WHERE model_number = 'S77S'), 'amazon', 'LG S77S WOW Orchestra Soundbar Review', 'The S77S delivers solid 3.1.3ch sound with WOW Orchestra support for compatible LG TVs. Dialogue clarity is excellent for the price range. The wireless subwoofer provides decent bass. Good mid-range option for those who want Dolby Atmos without breaking the bank. Setup is straightforward with HDMI eARC.', 'Amazon Customer', 4, 'positive', 0.76, 'https://www.amazon.com/dp/B0EXAMPLE', 'satisfaction', 3, 'actual_user', 'review', 'review_site', 'amz-s77s-001'),

-- S80TR Soundbar
((SELECT id FROM products WHERE model_number = 'S80TR'), 'rtings', 'LG S80TR 3.1.3ch Home Theater Soundbar', 'The S80TR is a good choice for those looking for LG TV compatibility. Offers 3.1.3ch setup with Dolby Atmos and DTS:X support. The design matches LG TV aesthetics perfectly. AI Room Calibration optimizes sound for your room. Solid mid-range option balancing performance and price.', 'RTINGS', 4, 'positive', 0.77, 'https://www.rtings.com/soundbar/reviews/lg/s80tr', 'satisfaction', 3, 'reviewer', 'review', 'review_site', 'rtings-s80tr-001')

ON CONFLICT DO NOTHING;